Added new effect name popping
NiallEccles/Hacktoberfest-animations pull request #265
Opened 2020-10-02 08:41 UTC by Akansha-Bhandari

2020-10-05 11:08 UTC, NiallEccles requested changes

2020-10-06 06:10 UTC, Akansha-Bhandari commented on animations/popping.css
> +  */
okii , Thanks for the feedback  
wiil do the changes ..

2020-10-07 12:38 UTC, Akansha-Bhandari reviewed
Did the changes as suggested ..
Can you please review them again ..

2020-10-07 13:53 UTC, NiallEccles requested changes
Just need one last change! Forgot to mention it before.

2020-10-07 13:53 UTC, NiallEccles commented on animations/popping.css
> +  }
Forgot to mention this bit - This will need to be updated to just be `.popping` rather than a `.wrapper` and `p`. For example, it would need to be this:

  .popping {
    font-size: 100px;
    font-family: Bowlby One SC, sans-serif;
    transform: scale(0.9, 1) rotatey(-10deg) translatey(0px);
    animation: 2.2s scaling cubic-bezier(0.45, 0, 0.55, 1) infinite;
    text-shadow: 0 0 #e8332e, 0 0 #fc9e05, 0 0 #891696;
    transform-origin: 50% 100%;
    color:white;
    position: relative;
    top: 10%;
    transform-style: preserve-3d;
    margin-right: 4px;

  }

2020-10-07 16:48 UTC, Akansha-Bhandari reviewed
Did the changes as mentioned..
Can you please have a look !

2020-10-07 16:56 UTC, NiallEccles commented
Yes! Looks good. I will update the `animations.js` file in your pull request just to make sure it is up-to-date with the rest of the repo!

2020-10-07 16:59 UTC, merged

2020-10-07 17:27 UTC, Akansha-Bhandari commented
Thank You :)