Added Water Wave Effect
NiallEccles/Hacktoberfest-animations pull request #280
Opened 2020-10-04 12:03 UTC by devarshidoshi

Added Water Wave Effect By Me

2020-10-04 12:05 UTC, devarshidoshi commented
Please Approve My Pull Request If You Love It

2020-10-05 11:36 UTC, NiallEccles requested changes

2020-10-05 11:36 UTC, NiallEccles commented on animations/Water.css
> +@import "compass/css3";
I think you need to remove this. Is there any reason why you need this?

2020-10-05 11:36 UTC, NiallEccles commented on animations/Water.css
> +  font-family: 'Cabin Condensed', sans-serif;
This font won't be available to those who do not have it installed on their machine. Could you use a Google Font? or a system font? That way anyone can view it.

2020-10-05 14:06 UTC, devarshidoshi commented on animations/Water.css
> +  font-family: 'Cabin Condensed', sans-serif;
Thanks for your response.. I have made the desired changes Thankk Youu

2020-10-06 08:57 UTC, NiallEccles commented
Nice! Great animation.

2020-10-06 08:57 UTC, merged

2020-10-06 09:37 UTC, devarshidoshi commented
Thankk Youu So Much!!