Issue 294
NiallEccles/Hacktoberfest-animations pull request #295
Opened 2020-10-07 19:39 UTC by strawberries73

Good afternoon.  I worked on this before sending you the issue.  I am done.  I am new at this, so please let me know how I did.

2020-10-07 20:17 UTC, NiallEccles requested changes
Thanks for submitting this! I just have one change for you to make. It is to add in the import statement for the font you are using.

2020-10-07 20:17 UTC, NiallEccles commented on animations/harvestflare.css
> +
Just need to add the `Staatliches` font import here `@import url('https://fonts.googleapis.com/css2?family=Staatliches&display=swap');`

2020-10-07 20:17 UTC, NiallEccles commented on animations/harvestflare.css
> +	font-family: 'Staatliches', cursive;
This font won't display unless you import that specific font or the user has it installed. Easy fix!

2020-10-08 02:54 UTC, strawberries73 commented on animations/harvestflare.css
> +
Ok, I shall do that.  Thank you!

2020-10-08 03:10 UTC, strawberries73 commented on animations/harvestflare.css
> +
Hello, I have made the changes. Is there anything else I can do?

2020-10-08 08:07 UTC, NiallEccles commented on animations/harvestflare.css
> +
Nope! That should be it. Have you made the changes to this request? I can't seem to see it right now. If you can update this request with that change I can merge!

2020-10-08 13:38 UTC, strawberries73 commented on animations/harvestflare.css
> +
I think I got it this time.  I am still getting acquainted with GitHub.

2020-10-08 13:47 UTC, NiallEccles commented on animations/harvestflare.css
> +
No problem! Glad to have your contribution!

2020-10-08 13:50 UTC, merged