Create hacktoberfestFlip.css
NiallEccles/Hacktoberfest-animations pull request #344
Opened 2020-10-19 14:06 UTC by saclig202

2020-10-20 09:29 UTC, NiallEccles requested changes
Thanks for submitting this. I have requested a few changes for you to make before I can accept.

2020-10-20 09:29 UTC, NiallEccles commented on animations/hacktoberfestFlip.css
> +}
This needs to go in `animations.js`

2020-10-20 09:29 UTC, NiallEccles commented on animations/hacktoberfestFlip.css
> +}
Can you remove these styles?

2020-10-20 09:29 UTC, NiallEccles commented on animations/hacktoberfestFlip.css
> +}
It's best to not have your styles on the body as they conflict with other users animations. Could you remove or integrate into your CSS class?

2020-10-20 09:29 UTC, NiallEccles commented on animations/hacktoberfestFlip.css
> +.hacktoberfestFlip span {
You don't need the `span` declaration here.

2020-10-20 09:29 UTC, NiallEccles commented on animations/hacktoberfestFlip.css
> +  animation-delay: calc(.2s * var(--i))
This CSS variable isn't declared anywhere. Could you update it to just be a regular time?

2020-10-27 14:10 UTC, saclig202 reviewed
I've made the requested changes.  If you need further changes to approve the pull request, I'll be happy to make them.  Thanks!

2020-10-28 14:17 UTC, closed without merging