Add cool css animation
NiallEccles/Hacktoberfest-animations pull request #462
Opened 2022-10-03 15:22 UTC by DenseOriginal

Added this cool moving gradiant animation

2022-10-03 16:08 UTC, NiallEccles requested changes
Hi 👋 Thanks for making this PR.

Can you update this PR to address the issue I have highlighted?

2022-10-03 16:08 UTC, NiallEccles commented on animations/text-color-gradiant.css
> +  display: inline-block;
Can you remove the `display: inline-block;` ?

2022-10-03 18:59 UTC, DenseOriginal commented on animations/text-color-gradiant.css
> +  display: inline-block;
Done

2022-10-04 12:54 UTC, NiallEccles commented
Nice! I love the colours 👏

2022-10-04 12:54 UTC, merged