Added Bouncing Reflection Text Animation
NiallEccles/Hacktoberfest-animations pull request #488
Opened 2022-10-06 12:58 UTC by Samar1110

Added bouncing with Reflection Text Animation
@NiallEccles please review and merge my PR for Hactoberfest-2022

2022-10-06 17:33 UTC, NiallEccles requested changes
Thanks for making this PR.

I've highlighted a few changes for you to make before I can merge!

2022-10-06 17:33 UTC, NiallEccles commented on animations/bouncing-with-reflection.css
> +}
Can you merge these styles into your CSS class?

2022-10-06 17:33 UTC, NiallEccles commented on animations/bouncing-with-reflection.css
> +  animation-delay: calc(.1s * var(--i));
Not really sure if this variable is supposed to be a CSS variable or comes from SASS

2022-10-06 17:33 UTC, NiallEccles commented on animations/bouncing-with-reflection.css
> +.waviy span {
You should remove the span selector and just have your class name.

2022-10-06 19:07 UTC, Samar1110 commented on animations/bouncing-with-reflection.css
> +}
Merged the Styles

2022-10-07 19:15 UTC, merged

2022-10-07 19:15 UTC, NiallEccles commented
Nice!