Added new animation - words dazing
NiallEccles/Hacktoberfest-animations pull request #493
Opened 2022-10-06 18:50 UTC by siddoinghisjob

2022-10-07 18:09 UTC, siddoinghisjob commented
Can you please accept this pr?

2022-10-07 19:22 UTC, NiallEccles requested changes
Thanks for making this PR.

Can you address the changes I've requested?

2022-10-07 19:22 UTC, NiallEccles commented on animations/WordComingDazzing.css
> +.heading{
Update this to be your animation name `.WordComingDazzing`

2022-10-08 12:02 UTC, siddoinghisjob commented
Have made the change 😸

2022-10-08 13:58 UTC, NiallEccles commented
Nice work 👏

2022-10-08 13:59 UTC, merged