Created ZoomInZoomOut animation file
NiallEccles/Hacktoberfest-animations pull request #508
Opened 2022-10-08 15:43 UTC by siddoinghisjob

2022-10-08 15:45 UTC, siddoinghisjob commented
Kindly let me know if any changes are required. If not, then please accept my PR.

2022-10-09 05:13 UTC, siddoinghisjob commented
@NiallEccles kindly accept my PR

2022-10-10 13:38 UTC, siddoinghisjob commented
@NiallEccles Can you please review this and merge if its alright?

2022-10-10 15:58 UTC, NiallEccles requested changes
Thanks for making this PR.

Can you take a look a the changes I've requested? You also need to add your animation to the `animations.js` file

2022-10-10 15:58 UTC, NiallEccles commented on animations/ZoomInZoomOut.css
> +        }
Can you move these into your CSS class?

2022-10-10 17:08 UTC, NiallEccles requested changes
Can you add your animation to the `animations.js` file?

2022-10-10 17:28 UTC, NiallEccles approved these changes

2022-10-10 17:28 UTC, merged